using EcsR3.Components;

namespace EcsR3.Examples.ExampleApps.Performance.Components.Specific
{
    public class Component1: IComponent {}
    public class Component2: IComponent {}
    public class Component3: IComponent {}
    public class Component4: IComponent {}
    public class Component5: IComponent {}
    public class Component6: IComponent {}
    public class Component7: IComponent {}
    public class Component8: IComponent {}
    public class Component9: IComponent {}
    public class Component10: IComponent {}
    public class Component11: IComponent {}
    public class Component12: IComponent {}
    public class Component13: IComponent {}
    public class Component14: IComponent {}
    public class Component15: IComponent {}
    public class Component16: IComponent {}
    public class Component17: IComponent {}
    public class Component18: IComponent {}
    public class Component19: IComponent {}
    public class Component20: IComponent {}
    public class Component21: IComponent {}
    public class Component22: IComponent {}
    public class Component23: IComponent {}
    public class Component24: IComponent {}
    public class Component25: IComponent {}
    public class Component26: IComponent {}
    public class Component27: IComponent {}
    public class Component28: IComponent {}
    public class Component29: IComponent {}
    public class Component30: IComponent {}
    public class Component31: IComponent {}
    public class Component32: IComponent {}
    public class Component33: IComponent {}
    public class Component34: IComponent {}
    public class Component35: IComponent {}
    public class Component36: IComponent {}
    public class Component37: IComponent {}
    public class Component38: IComponent {}
    public class Component39: IComponent {}
    public class Component40: IComponent {}
    public class Component41: IComponent {}
    public class Component42: IComponent {}
    public class Component43: IComponent {}
    public class Component44: IComponent {}
    public class Component45: IComponent {}
    public class Component46: IComponent {}
    public class Component47: IComponent {}
    public class Component48: IComponent {}
    public class Component49: IComponent {}
    public class Component50: IComponent {}
    public class Component51: IComponent {}
    public class Component52: IComponent {}
    public class Component53: IComponent {}
    public class Component54: IComponent {}
    public class Component55: IComponent {}
    public class Component56: IComponent {}
    public class Component57: IComponent {}
    public class Component58: IComponent {}
    public class Component59: IComponent {}
    public class Component60: IComponent {}
    public class Component61: IComponent {}
    public class Component62: IComponent {}
    public class Component63: IComponent {}
    public class Component64: IComponent {}
    public class Component65: IComponent {}
    public class Component66: IComponent {}
    public class Component67: IComponent {}
    public class Component68: IComponent {}
    public class Component69: IComponent {}
    public class Component70: IComponent {}
    public class Component71: IComponent {}
    public class Component72: IComponent {}
    public class Component73: IComponent {}
    public class Component74: IComponent {}
    public class Component75: IComponent {}
    public class Component76: IComponent {}
    public class Component77: IComponent {}
    public class Component78: IComponent {}
    public class Component79: IComponent {}
    public class Component80: IComponent {}
    public class Component81: IComponent {}
    public class Component82: IComponent {}
    public class Component83: IComponent {}
    public class Component84: IComponent {}
    public class Component85: IComponent {}
    public class Component86: IComponent {}
    public class Component87: IComponent {}
    public class Component88: IComponent {}
    public class Component89: IComponent {}
    public class Component90: IComponent {}
    public class Component91: IComponent {}
    public class Component92: IComponent {}
    public class Component93: IComponent {}
    public class Component94: IComponent {}
    public class Component95: IComponent {}
    public class Component96: IComponent {}
    public class Component97: IComponent {}
    public class Component98: IComponent {}
    public class Component99: IComponent {}
    public class Component100: IComponent {}
}