name: Build And Test
on: [push]

env:
  BUILD_VERSION: '8.0.${{github.run_number}}'
  SOLUTION_FILE: 'src/EcsR3.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 9.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Build
        run: dotnet restore ${{SOLUTION_FILE}}
      - name: Build
        run: dotnet build --configuration Release -p:Version=${{ env.BUILD_VERSION }} ${{SOLUTION_FILE}}
      - name: Test
        run: dotnet test --configuration Release --no-build ${{ env.SOLUTION_FILE }}